[package]
name = "build-tree-sitter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc = "1.0"
log = "0.4"
anyhow = "1.0"
colored = "2.0"
pretty_env_logger = "0.5.0"
